#!/bin/sh
# KVAS bootstrap installer for an Entware-enabled Keenetic router.
# Usage (public repository):
#   curl -fsSL https://raw.githubusercontent.com/shamanWeb/kvasec/master/install.sh | sh
#   wget -qO- https://raw.githubusercontent.com/shamanWeb/kvasec/master/install.sh | sh
# For a private repository pass KVAS_GITHUB_TOKEN (Contents: read) to curl and
# this script; it will be saved for later `kvas upgrade` calls.

set -eu

REPO=${KVAS_REPO:-shamanWeb/kvasec}
API_URL="https://api.github.com/repos/${REPO}/releases/latest"
TMP_DIR=${KVAS_TMP_DIR:-/opt/tmp}
TOKEN=${KVAS_GITHUB_TOKEN:-}
TOKEN_FILE=/opt/etc/kvas.github.token
TMP_IPK=""
TMP_SHA=""

cleanup() {
    [ -n "$TMP_IPK" ] && rm -f "$TMP_IPK"
    [ -n "$TMP_SHA" ] && rm -f "$TMP_SHA"
}
trap cleanup EXIT HUP INT TERM

fail() { printf 'KVAS install: %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || fail 'run as root on the router'
command -v opkg >/dev/null 2>&1 || fail 'Entware is not installed (opkg not found)'
mkdir -p "$TMP_DIR" || fail "cannot create $TMP_DIR"

if [ -z "$TOKEN" ] && [ -s "$TOKEN_FILE" ]; then
    TOKEN=$(tr -d ' \r\n' < "$TOKEN_FILE")
fi

download() {
    # $1 URL, $2 destination.  Both curl and wget are common on Entware.
    if command -v curl >/dev/null 2>&1; then
        if [ -n "$TOKEN" ]; then
            curl -fsSL --connect-timeout 15 --retry 2 -H "Authorization: Bearer $TOKEN" "$1" -o "$2"
        else
            curl -fsSL --connect-timeout 15 --retry 2 "$1" -o "$2"
        fi
    elif command -v wget >/dev/null 2>&1; then
        if [ -n "$TOKEN" ]; then
            wget -q -O "$2" --header="Authorization: Bearer $TOKEN" "$1"
        else
            wget -q -O "$2" "$1"
        fi
    else
        fail 'curl or wget is required'
    fi
}

TMP_API=$(mktemp "${TMP_DIR}/kvas-release.XXXXXX") || fail 'cannot create temporary file'
TMP_IPK=$(mktemp "${TMP_DIR}/kvasec-ipk.XXXXXX") || fail 'cannot create temporary file'
TMP_SHA=$(mktemp "${TMP_DIR}/kvasec-sha.XXXXXX") || fail 'cannot create temporary file'
trap 'rm -f "$TMP_API"; cleanup' EXIT HUP INT TERM

printf '%s\n' 'Fetching latest KVAS release…'
download "$API_URL" "$TMP_API" || fail 'cannot read latest GitHub release (a token may be required)'

# Asset URLs are JSON strings.  Release assets are generated by this project,
# so selecting the SemVer-named IPK is deterministic and avoids an arbitrary
# URL supplied through an environment variable.
IPK_URL=$(sed -n 's/.*"browser_download_url"[[:space:]]*:[[:space:]]*"\([^"]*\/kvasec_[0-9][0-9.]*\.ipk\)".*/\1/p' "$TMP_API" | head -1)
[ -n "$IPK_URL" ] || fail 'the latest release has no kvasec_*.ipk asset'

printf '%s\n' "Downloading ${IPK_URL##*/}…"
download "$IPK_URL" "$TMP_IPK" || fail 'package download failed'
[ -s "$TMP_IPK" ] || fail 'downloaded package is empty'

# New releases publish a SHA-256 sidecar.  Old releases remain installable,
# but are explicitly reported as unverified rather than silently trusted.
if download "${IPK_URL}.sha256" "$TMP_SHA" 2>/dev/null && [ -s "$TMP_SHA" ] && command -v sha256sum >/dev/null 2>&1; then
    expected=$(awk 'NR==1 {print $1}' "$TMP_SHA")
    actual=$(sha256sum "$TMP_IPK" | awk '{print $1}')
    [ -n "$expected" ] && [ "$expected" = "$actual" ] || fail 'SHA-256 mismatch; package was not installed'
    printf '%s\n' 'SHA-256 verified.'
else
    printf '%s\n' 'Warning: release has no SHA-256 file; installing over HTTPS without checksum verification.' >&2
fi

printf '%s\n' 'Updating Entware package lists…'
opkg update || fail 'opkg update failed'
printf '%s\n' 'Installing KVAS…'
opkg install --force-reinstall "$TMP_IPK" || fail 'opkg installation failed'

if [ -n "${KVAS_GITHUB_TOKEN:-}" ]; then
    mkdir -p "$(dirname "$TOKEN_FILE")"
    ( umask 077; printf '%s\n' "$TOKEN" > "$TOKEN_FILE" )
    chmod 600 "$TOKEN_FILE" 2>/dev/null || true
    printf '%s\n' 'GitHub token saved for future kvas upgrade calls.'
fi

printf '%s\n' 'KVAS installed. For a first installation run: kvas setup'
